### ISSUE TITLE
Can I testing go binary cross compiled for ARM on this emulator?

### ISSUE THREAD

**Issue by DeadNumbers** [coderick14/ARMed#1]

**Comment by coderick14** [comment]
Hey. Thanks for your interest. Can you elaborate your doubt a little, please?

**Comment by DeadNumbers** [comment]
I'm looking for an emulator to test my programs compiled for ARM. At present, QEMU does not support Go  https://github.com/golang/go/issues/13024#issuecomment-164894790 I found in Google a link to this repository and would like to know if I can test my programs in this emulator.

**Comment by coderick14** [comment]
As of now, it doesn't support execution of cross compiled Go binaries. But thanks for pointing it out. Will try to incorporate this feature.

**Comment by Sriharshakp** [comment]
What is this?
